# Generated by Django 4.0.4 on 2023-12-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_time',
            field=models.DateTimeField(),
        ),
    ]
