# Generated by Django 4.0.4 on 2023-12-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_report_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_time',
            field=models.CharField(max_length=100),
        ),
    ]
