# Generated by Django 4.0.4 on 2023-12-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_report_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_project',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assigned_project',
            name='start_time',
            field=models.DateField(),
        ),
    ]
