# Generated by Django 4.0.4 on 2023-12-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_assigned_project_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_project',
            name='end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assigned_project',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
