# Generated by Django 4.0.4 on 2023-12-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_assigned_project_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_project',
            name='employee_id',
            field=models.CharField(max_length=100),
        ),
    ]
