# Generated by Django 5.0 on 2024-01-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_assigned_project_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_emp',
            name='gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
